### ISSUE TITLE
Create Kanban board

### ISSUE THREAD

**Issue by williamrolando88** [williamrolando88/Recipe-app#7]
Hi,

We are a team of 2 people:
 - @Mre55 
 - @williamrolando88 

This is our [Kanban board](https://github.com/williamrolando88/Recipe-app/projects/1), here you can see how we split the tasks given for this project.

The group task was assigned to @williamrolando88 as requested:
>Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees. NOTE you should distribite tasks in a way that gives each team member a chance to work with different parts of RoR. The number of assigned points should be equal (+/- 5 points) for each member.

**Comment by andersonlebon** [comment]
## Hi team @williamrolando88  && @Mre55 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by andersonlebon** [comment]
## OPTIONAL
- [ ] Kindly I would really suggest you make the group tasks pair programming. So that both parties get the idea of how the project is progressing even if the requirements say:point_down: 

> Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees. NOTE you should distribute tasks in a way that gives each team member a chance to work with different parts of RoR. The number of assigned points should be equal (+/- 5 points) for each member.
